subscription {
  Porudzbina {
			node {
        id,
        adresa,
        brojTelefona,
        opis,
        stavkePorudzbines {
          id,
          kolicina,
          proizvod {
            naslov
          }
        }
      }
    }
}
