query AllPorudzbinas {
  allPorudzbinas {
    id,
    adresa,
    vreme,
    opis,
    brojTelefona,
    createdAt,
    stavkePorudzbines{
      id,
      kolicina,
      proizvod {
        naslov,
      }

    }
  }
}
