query AllPorudzbinas {
  allPorudzbinas {
    id,
    adresa,
    vreme,
    opis,
    brojTelefona,
    createdAt,
    potvrdjen,
    uredjaj,
    stavkePorudzbines{
      id,
      kolicina,
      prilozi,
      uSomunu,
      proizvod {
        naslov,
        tip,

      }

    }
  }
}
